services:
  - type: web
    name: bomb-card-game-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_PASSWORD
        value: $2b$10$YourHashedPasswordHere
